title: I Tandura
description: Tandura Storia
url: http://tandura-storia.aavv.io
avatar: http://tandura-storia.aavv.io/book/assets/img/avatar.jpg
favicon: http://tandura-storia.aavv.io/assets/img/favicon.ico
google_analytics: UA-xxxx-1
disqus_shortname: xxxx

about:
  - paragraph: ?link?, a simple Jekyll theme. Built by ?link?
    text_align: center
    links:
      - name: Book
        url: https://github.com/kkninjae/book
        external: true
      - name: Lang Liu
        url: http://kkninjae.com/about/
        external: false

    
